[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OctoPrint-TapoAutoShutdown"
version = "0.3.0"
description = "Automatically control a Tapo P110 and manage Obico AI monitoring around your prints."
authors = [
    {name = "SpideRaY", email = "spideray.me@gmail.com"}
]
readme = {file = "README.md", content-type = "text/markdown"}
dynamic = [
    "license"
]

requires-python = ">=3.11, <4"

dependencies = [
    "tapo>=0.10.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = [
    "octoprint_tapoautoshutdown",
    "octoprint_tapoautoshutdown.*"
]

[tool.setuptools.package-data]
octoprint_tapoautoshutdown = [
    "templates/*.jinja2",
]

[project.entry-points."octoprint.plugin"]
tapoautoshutdown = "octoprint_tapoautoshutdown"

[project.urls]
Homepage = "https://github.com/SpideRaY/OctoPrint-TapoAutoShutdown-ObicoDelay"

[project.optional-dependencies]
develop = [
    "go-task-bin"
]
